name = "SeisMain"
uuid = "5696fd22-15e8-11e9-1986-f9ab08703604"
authors = ["fercarozzi <carozzi@ualberta.ca>"]
version = "0.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
DocumentationGenerator = "8f0d3306-d70b-5309-b898-24bb6ab47850"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "~0.23"
DocumenterTools = "~0.1"
julia = "1"
